{
 "title": "Real-time monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raman Predict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"Time stream\" AT TIME ZONE 'UTC-7' AT TIME ZONE 'UTC' AS \"time\",\r\n  \"Cust\",\"Project_ID\",\r\n  AVG(prediction) as \"Predict\"\r\nFROM raman_db\r\nGROUP BY \"Cust\",\"time\",\"Project_ID\"\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Raman_Number of BatchID by Cust",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Cust\",\n  \"Project_ID\",\n  count(\"BatchID\") as \"Number of BatchID\"\nFROM raman_db\nGROUP BY \"Cust\",\"Project_ID\""
    }
   ]
  },
  {
   "title": "Operation_Number of BatchID by Cust",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Cust\",\n  \"Project_ID\",\n  count(\"BatchID\") as \"Number of BatchID\"\nFROM operation_db\nGROUP BY \"Cust\",\"Project_ID\""
    }
   ]
  },
  {
   "title": "Operation Predict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Time_stream\" AT TIME ZONE 'UTC-7' AT TIME ZONE 'UTC' AS \"time\",\n  \"Cust\",\"Project_ID\",\n  AVG(prediction) as \"Predict\"\nFROM operation_db\nGROUP BY \"Cust\",\"time\",\"Project_ID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Time_stream\" AT TIME ZONE 'UTC-7' AT TIME ZONE 'UTC' AS \"time\",\n  \"Cust\",\n  AVG(\"Temperature\") as \"Temperature\"\nFROM operation_db\nGROUP BY \"Cust\",\"time\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Operation_Number of Predict By Cust",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Cust\",\"Project_ID\",\n  Count(prediction) as \"Predict\"\nFROM operation_db\nGROUP BY \"Cust\",\"Project_ID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Raman_Number of Predict By Cust",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Cust\",\"Project_ID\",\n  Count(prediction) as \"Predict\"\nFROM raman_db\nGROUP BY \"Cust\",\"Project_ID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Operation Newest Values",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n \"Time_stream\" AT TIME ZONE 'UTC-7' AT TIME ZONE 'UTC' AS \"time\",\n  \"Cust\",\"Project_ID\",\"BatchID\",\"prediction\"\nFROM operation_db\nORDER BY \"time\" desc"
    }
   ]
  }
 ]
}