apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: ktech_postgresql:5432
    database: bio
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: "disable"
      maxOpenConns: 50
      maxIdleConns: 10
      connMaxLifetime: 14400
    isDefault: true
